### ISSUE TITLE
Jupyter Server Notes 2020

### ISSUE THREAD

**Issue by Zsailer** [jupyter-server/team-compass#1]
## Hello everyone,

[![Gitter](https://badges.gitter.im/jupyter/jupyter_server.svg)](https://gitter.im/jupyter/jupyter_server?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

*Welcome to the Jupyter Server Team!*

You can find us in our [Gitter chat room](https://gitter.im/jupyter/jupyter_server) or visit us at our weekly meetings!

We meet on Thursdays at 8:00am, Pacific Standard Time on [Jupyter's Zoom Channel](https://zoom.us/j/2264645576?pwd=c0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09). You can add yourself to the weekly [agenda here](https://hackmd.io/Wmz_wjrLRHuUbgWphjwRWw). **Everyone is welcome!** 

Let's avoid using this thread for discussion. If you'd like to discuss something in the minutes, open a separate issue and reference this thread.

## Meeting Minutes

* [December 17th, 2020](https://github.com/jupyter-server/team-compass/issues/1#issuecomment-747557046)
* [December 10th, 2020](https://github.com/jupyter-server/team-compass/issues/1#issuecomment-742705421)
* [December 3rd, 2020](https://github.com/jupyter-server/team-compass/issues/1#issuecomment-738148830)
* November 26th, 2020 - no meeting (US Holiday - Thanksgiving)
* [November 19th, 2020](https://github.com/jupyter-server/team-compass/issues/1#issuecomment-730514597)
* [November 12th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-726211809)
* [November 5th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-722505254)
* [October 29th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-719057742)
* [October 22nd, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-714607823)
* October 15th, 2020 - no meeting for JupyterCon 2020
* October 8th, 2020 - no meeting for JupyterCon 2020
* October 1st, 2020 - no minutes captured (sorry about that)
* [September 24th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-698444387)
* [September 17th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-694338462)
* [September 10th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-694318346)
* [September 3rd, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-686603111)
* [August 27th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-682032319)
* [August 20th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-681982773)
* [August 13th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-6736540710)
* [August 6th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-670584627)
* [July 30th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-669989903)
* [July 23rd, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-666423029)
* [July 16th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-662834380)
* [July 9th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-656343178)
* [July 2nd, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-653119898)
* [June 25th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-653060185)
* [June 18th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-649628444)
* [June 11th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-642809571)
* [June 4th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-642808781)
* [May 28th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-636928298)
* [May 21st, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-632334779)
* [May 14th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-628734179)
* [May 7th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-628691315)
* [April 30th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-624917608)
* [April 23rd, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-619251869)
* [April 16th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-616705824)
* [April 9th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-614326322)
* [April 2nd, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-610744841)
* [March 26th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-604576053)
* [March 19th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-604487671)
* [March 12th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-599620638)
* [March 5th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-595350953)
* [February 27th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-592074805)
* February 20th, 2020—meeting canceled.
* [February 13th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-585861292)
* [February 6th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-583047516)
* [January 30th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-580397596)
* [January 16th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-576810678)
* [January 9th, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-572685339)
* [January 2nd, 2020](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-570270831)
* December 12th, 2019—[no meeting](https://github.com/jupyter/jupyter_server/issues/158).
* [December 5th, 2019](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-562291613)
* [November 21st, 2019](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-562291060)
* [November 7th, 2019](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-551176009)
* [October 31st, 2019](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-549600862)
* [October 24th, 2019](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-546049016)
* [October 17th, 2019](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-545577061)
* [October 10th, 2019](https://github.com/jupyter/jupyter_server/issues/126#issuecomment-545576616)

**Comment by Zsailer** [comment]
## November 19th, 2020


### Attendees

| Name          | affiliation      | username     |
| ------------- | ---------------- | ------------ |
| Kevin Bates | IBM | @kevin-bates |
| Zach Sailer | Apple | @Zsailer |
| Jeremy Tuloup | QuantStack | @jtpio |
| A. T. Darian | Two Sigma | @afshin |

### Agenda + Minutes

- [Kevin] 
    - PRs released to prefix fixtures and removed previous plugin and entrypoint (Thanks to Nick Bollweg - @bollwvyl!). Release 1.0.6 (thanks Zach) can be used by apps using the non-prefixed fixtures.
    - Release 1.1 will be coming out soon. We need to get a patch into lab's test framework for prefixing the server-related fixtures prior to the release
    - I will be looking at the async contents PR (https://github.com/jupyter/jupyter_server/pull/324)
        - Would be good if others could check this out as well
    - Ported a couple more Notebook PRs, plenty to go still
    - I will be out starting 12/2 through 1/3 - Happy New Year - good riddance 2020!

- [Jeremy]
    - Should [nbresuse](https://github.com/yuvipanda/nbresuse) move to [jupyter-server](https://github.com/jupyter-server)?
        - Yes.  We will move to the jupyter-server org with a long-term goal of baking into the server and "closer" to kernels

- [Zach]
    - Added steering council members as managers of jupyter-server org.
    - Move Jupyter Server to new org in this meeting, today!
    - Done! :tada:

**Comment by kevin-bates** [comment]
## December 3rd, 2020

### Attendees

| Name          | affiliation      | username     |
| ------------- | ---------------- | ------------ |
| Pierre-Olivier Simonard | ioapps.io / Quansight | @pierrotsmnrd | 
| Zach Sailer | Apple |  @Zsailer |
| Kevin Bates | IBM | @kevin-bates |
| Mariko Wakabayashi | | @mwakaba2




### Agenda + Minutes

- Async ContentsManager [PR #324](https://github.com/jupyter-server/jupyter_server/pull/324)
    - Current State:
    - Next Steps:
- Extension discovery for Python-based extensions [Issue #351](https://github.com/jupyter-server/jupyter_server/issues/351)
- Projects that might move to Server org:
    - jupyter-archive [Issue #251](https://github.com/jupyter-server/jupyter_server/issues/251)
    - nbclassic

**Comment by Zsailer** [comment]
## December 10th, 2020

:::info
**Time:** 8:00AM Pacific (your [timezone](https://arewemeetingyet.com/Los%20Angeles/2019-10-24/08:00/w/Jupyter%20Server%20Meeting))
**Where:** [Zoom Channel](https://zoom.us/my/jovyan?pwd=c0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09) (pwd: c0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09)
:::

### Attendees

| Name          | affiliation      | username     |
| ------------- | ---------------- | ------------ |
| Zach Sailer | Apple | @Zsailer | 
| Kevin Bates | IBM | @kevin-bates |


### Agenda + Minutes

* Backport #340 to 1.0.x branch. 
    * This was missed in the backport of #350.
    * PR https://github.com/jupyter-server/jupyter_server/pull/359
    * Release a v1.0.10 with this PR.
* Move pytest_plugin back into Jupyter Server from pytest-jupyter.
    * Open a PR in jupyter_core with the fixtures that are jupyter_core specific.
    * We don't need to wait for the jupyter_core side. We'll include a duplicate of those fixtures in Jupyter Server temporarily, then remove later.
* Plan to release 1.1 Friday.
    * Merge Async Contents changes ([#324](https://github.com/jupyter-server/jupyter_server/pull/324)) today.
    * Merge pytest_plugin work today.
    * Release 1.1 by tomorrow, EOD (pacific).
    * Bump jupyter_server version in JupyterLab and JupyterLab Server.

**Comment by Zsailer** [comment]
:tada:  Next Thursday is our last meeting of the year! 🎉   (After that, it's Christmas Eve  🎅  and New Year's Eve). 

Wear your ugly holiday sweater is you have one! :wink:

**Comment by Zsailer** [comment]
## December 17th, 2020

### Attendees

| Name          | affiliation      | username 
| ------------- | ---------------- | ------------
| Zach Sailer | Apple | @Zsailer 
| A. T. Darian | Two Sigma | @afshin |
| Jeremy Tuloup | QuantStack | @jtpio |
| Kevin Bates | IBM | @kevin-bates|
| Vidar T Fauske | JP Morgan | @vidartf |



### Agenda + Minutes

* Deprecated the pytest-jupyter plugin.
    * Jupyter Server has its own pytest_plugin now.
    * Documentation on this plugin will be added to the jupyter_server docs.
    * Pytest-jupyter might become a "best practices" page for pytest around Jupyter.
* Released 1.1.1 patch yesterday.
    * Security Advisory Published.
    * Minor fix in Async Contents API: https://github.com/jupyter-server/jupyter_server/pull/363
* Notebook server and jupyter server extensions in one dist? https://github.com/jupyter/nbdime/pull/551
    * Server extensions *should be* both forwards and backwards compatible.
        * Jupyter Server's new `JupyterHandler` currently works with classic notebook server.
        * Notebook's `IPythonHandler` works with Jupyter Server.
* Min's student, Kien, is working Telemetry in Jupyter Server.
    * Concerns about posting to `/api/endpoint`.
    * Posting events to the server without properly checking who "owns" the event seems like a problem.
* Published [jupyter-resource-usage](https://github.com/jupyter-server/jupyter-resource-usage) to PyPI
    * Invited a couple of people as maintainers / owners
    * Next: conda-forge
    * Jeremy has another resource usage extension, https://github.com/jtpio/jupyterlab-system-monitor.
        * Move this into jupyter-resource-usage.
        * Deprecate th

**Comment by Zsailer** [comment]
I've opened a new issue for meeting notes in 2021. Let's leave this issue open through January 2021, then close it.
