### ISSUE TITLE
Plans for hosting a Weekly "Contributing" Hour

### ISSUE THREAD

**Issue by Zsailer** [jupyter-server/team-compass#21]
We'll meet at **9am PST** on the [Joyvan Zoom channel](https://zoom.us/my/jovyan?pwd=c0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09) for a weekly "Contributing" hour. See the details below! 🚀 

Come join us! Everyone is welcome!

----------------

Over the past couple of Jupyter Server meetings, we've discussed the idea of a "contributing" hour (the name isn't final 😆). 

The goal was to create a place for anyone to visit, observe, and learn from Jupyter Server team members and contributors. The hope is that we can help accelerate new, interested people towards becoming regular contributors to the project and grow the Jupyter Server community.

During this hour, team members might help new people set up a development environment, give a tour of the codebase, discuss areas under current development, answer questions, etc. Otherwise, one of the team members will pick an issue or feature tackle together. This person will "drive"—live coding and screensharing—while the rest of the group "pair programs" with them. 

I'd like to start this hour sometime next week. I propose the following two options for meeting times:
1. We meet right after the Jupyter Server meeting, **Thursday at 9AM PST**. This conflicts with the Triaging group and would require us to work with them to determine a time/place.
2. We meet on **Friday at 8AM PST** on the Jupyter Zoom Channel.

Let me know your availability in the comments below ASAP and I'll work out a time/place.

**Comment by Zsailer** [comment]
@jupyter-server/active-team-members

**Comment by blink1073** [comment]
I'd prefer afterward

**Comment by kevin-bates** [comment]
Thanks for driving this @Zsailer.

I suppose I'd prefer afterward as well, although I have a conflict at that time (Elyra community call) :smile: - so my participation would likely be conditional (based on the topic, which is probably the case regardless).

**Comment by mwakaba2** [comment]
+1 on meeting right after the Jupyter Server meeting! (For next week, I do have a meeting between 9am and 9:30 PST, but I hope to attend the second half of the session.)

**Comment by lresende** [comment]
Same conflict as @kevin-bates.

**Comment by ivanov** [comment]
I wasn't able to join it this past week, but Jupyter Lab and Notebook Triage meeting the week prior fell to the Thursday 9am PST slot and that was quite fun, so it'd be a shame to have two Jupyter things conflicting. I'd prefer Friday 8am PST slot for that reason, but would otherwise be OK with either of those.

**Comment by Zsailer** [comment]
I've been chatting with @tonyfast and @jweill-aws about the conflict with the Triaging meeting through email. 

We've been discussing moving the triage meeting back to 10AM PST to allow this group to host this "Contributing" hour right after the Jupyter Server meeting, given the response here.

**Comment by Zsailer** [comment]
Let's see how this week goes and we can adjust for next week if needed.

This week, we will:
* host the Jupyter Server "Contributing" hour Thursday, 9-10AM PST (right after the Jupyter Server meeting).
* host the Triaging Meeting at 10AM PST on Thursday

**Comment by Zsailer** [comment]
Closing in favor of #22
