### ISSUE TITLE
[ANNOUNCEMENT] Weekly "Contributing" Hour

### ISSUE THREAD

**Issue by Zsailer** [jupyter-server/team-compass#22]
**Details**

The Jupyter Server Team is hosting a weekly "Contributing" hour. 

We'll meet **Thursday at 9am PST** on the [Joyvan Zoom channel](https://zoom.us/my/jovyan?pwd=c0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09).

Come join us! Everyone is welcome!

**Summary** 

This is a place for anyone to visit, observe, and learn from Jupyter Server team members and contributors. The hope is that we can help accelerate new, interested people towards becoming regular contributors to the project and grow the Jupyter Server community. 

During this hour, team members can help new people set up a development environment, give a tour of the codebase, discuss areas under current development, answer questions, etc. Otherwise, one of the team members will pick an issue or feature to tackle together. This person will "drive"—live coding and screen sharing—while the rest of the group "pair programs" with them. 

If you're curious about contributing to Jupyter open-source projects, feel free to stop by and just watch. 😃  

Keep in mind, this hour is focused on learning how to contribute to open-source Jupyter Server (and possibly other Jupyter subprojects). **This is not a place** to ask questions about how to write custom extensions, deploy Jupyter for your enterprise, etc. We recommend that you ask these questions on the Jupyter Discourse page.

**Comment by Zsailer** [comment]
Created this post to give us somewhere to point new-comers! 🚀

**Comment by Zsailer** [comment]
We've created the following repo, https://github.com/jupyter-server/contributing-hour, to host code/examples/demos we create together during this hour. It's a great place to review all the great things we learn together!

Check it out!

**Comment by jabbera** [comment]
Does this still happen? I'm motivated to make some changes in voila, but I'm stymied by the jupyter_server 2.0 changes and what the best approach is for upgrading

**Comment by 3coins** [comment]
@jabbera 
Yes, this still happens, although I would suggest to join a bit early for the Jupyter Server meeting from 8-9am PST where you can ask specific questions about 2.0.

**Comment by jabbera** [comment]
@3coins thanks I'll take you up on that if I can't get this squared away asynchronously. I'm motivated to get voila supporting 2.0 but I've hit my first roadblock. What's not clear to me is what to do about the following part of the implementation: 

https://github.com/jabbera/voila/blob/7334c00cec2ad47c66533d360ad59adb37abfa54/voila/app.py#L40
https://github.com/jabbera/voila/blob/7334c00cec2ad47c66533d360ad59adb37abfa54/voila/app.py#L495

There seems to be an implicit assumption in the commit comment where ZMQChannelsHandler that this class would be "forked". I can't find an example anywhere of a similar usage that has been upgraded and I feel like I'm missing something incredibly obvious.

**Comment by kevin-bates** [comment]
Hi @jabbera - The [ZMQChannelsHandler was refactored in 2.0](https://github.com/jupyter-server/jupyter_server/pull/1047).  I _think_ the references to `ZMQChannelsHandler` can be replaced with `KernelWebsocketHandler` - which resides in `jupyter_server.services.kernels.websocket` in 2.0.  I'm just not sure if its a straight-up replacement.

cc: @Zsailer

**Comment by jabbera** [comment]
Many thanks. I'll give it a go.

**Comment by Zsailer** [comment]
To anyone watching this issue, I will be stepping away from running these "Contributing Hours" for the time being. 

I'm a bit over-committed right now and feel a bit guilty that I haven't been able to reliably run these calls. 

That said, I love this concept and hope to see it pick up again very soon. It's such a fun way to learn and grow as a team and community. If anyone else is interested if leading these, I'd love to support you! I'm happy to share my experience and offer any tips to get things going again. ❤️
