### ISSUE TITLE
Jupyter Server 2.0

### ISSUE THREAD

**Issue by Zsailer** [jupyter-server/team-compass#24]
It looks like the new [Identity API ](https://github.com/jupyter-server/jupyter_server/pull/671)might need to introduce some backwards incompatible changes, warranting a[ new major release of Jupyter Server (i.e. 2.0).](https://github.com/jupyter-server/jupyter_server/pull/671#issuecomment-1077888025) 

I am opening this issue for two reasons:
1. make everyone aware of this change to avoid inadvertently publishing this feature in a 1.x release.
2. discuss a strategy for branching and releasing going forward. 

I'll do some poking around other Jupyter subprojects to see how these things are managed elsewhere. In the meantime, if anyone wants to provide their own insights, feel free to comment below. 

Thanks!

**Comment by blink1073** [comment]
I created a 2.0 milestone and also added https://github.com/jupyter-server/jupyter_server/pull/651

**Comment by echarles** [comment]
Replying here on comment from @fcollonval https://github.com/jupyter-server/team-compass/issues/15#issuecomment-1092579582

> > Is needed for JupyterLab 4.0, i.e. before June? No.
>
> I disagree on that point. Identity is needed for RTC and we certainly hope to get a first decent RTC experience in 4.0.

I am +0.5 :) on @fcollonval comment. There are other features needed to bring that `decent` RTC experience in 4.0. :)

As the identity API is a needed building block for RTC, I agree jlab-4 depending on jserver-2 would be a good fit.

**Comment by vidartf** [comment]
We're well on the way to a 2.0 release, so I think we have resolved the points brought up in the issue.
