### ISSUE TITLE
Use of pre-commit

### ISSUE THREAD

**Issue by blink1073** [jupyter-server/team-compass#25]
## Description
I added the https://pre-commit.ci/ GitHub App to the org.  By default this means that any repo with a `.pre-commit-config.yaml` file will get a weekly PR to update the versions used.  This will help us keep them up to date easier.

cf https://github.com/jupyterlab/jupyterlab/issues/12272

**Comment by vidartf** [comment]
I hope this should have reached the intended audience by now :)
