### ISSUE TITLE
[Proposal: new repo] Synchronizer extension

### ISSUE THREAD

**Issue by Zsailer** [jupyter-server/team-compass#26]
Hi all, 

After some discussion in https://github.com/jupyter-server/jupyter_server/pull/752, I'd like to move this logic into its own extension and repository under this organization. Much like the "terminals" extension, I don't think this belongs in the core APIs, but makes a nice addition to Jupyter servers that serve remote kernels. 

Moving it into its own repository allows us to more easily collaborate on this extension during the early experimental phases. 

Before creating the repo in this org, I'd like to check for consensus from @jupyter-server/active-team-members. Creating new repos always presents the risk of additional maintenance burden. 

Any objections?

**Comment by Zsailer** [comment]
> Will we make a recommendation to JupyterLab and Jupyter Notebook to ship with this extension by default

No, I don't think so. This isn't really needed for Jupyter Servers with local kernels or contents (which is the default for most of our users).

**Comment by afshin** [comment]
Cool, thanks for the clarification!

**Comment by Zsailer** [comment]
Thanks, all. 

I created the repo and have an initial PR here: https://github.com/jupyter-server/synchronizer/pull/1
