### ISSUE TITLE
Vote: transfer jupyter_ydoc to jupyter-server

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-server/team-compass#29]
From [this issue](https://github.com/jupyter-server/jupyter_server/issues/816):

### Problem

With the ongoing work in [JupyterLab around RTC](https://github.com/jupyterlab/jupyterlab/pull/12360), we are starting to create back-end [shared document structures](https://github.com/jupyterlab/jupyterlab/blob/c059bbc921dd66868bc457407ab8d3d938f78548/jupyterlab/handlers/ydoc.py) that shouldn't be tied to JupyterLab in particular. I can imagine e.g. a Python web client that would need these document structures as well, it shouldn't need to depend on JupyterLab.
We currently have:
- `class YFile(YBaseDoc)`: a document class for a generic text document.
- `class YNotebook(YBaseDoc)`: a document class for a notebook.

These classes currently have methods to:
- get initialized from a source (text/JSON).
- get exported to text/JSON.
- observe changes to the document.

### Proposed Solution

I started https://github.com/davidbrochart/jupyter_ydoc. It's still in development but it already supports [jupyter_releaser](https://github.com/jupyter-server/jupyter_releaser).
Please comment on this issue or just use :+1: / :-1: if you agree/disagree on transferring it to `jupyter-server`.

**Comment by SylvainCorlay** [comment]
👍

**Comment by echarles** [comment]
+1

**Comment by davidbrochart** [comment]
I am not expecting too many votes for this kind of small library, so I will transfer jupyter_ydoc today.

**Comment by davidbrochart** [comment]
Done: https://github.com/jupyter-server/jupyter_ydoc
