### ISSUE TITLE
Move nbresuse into jupyter-server organization

### ISSUE THREAD

**Issue by Zsailer** [jupyter-server/team-compass#3]
We discussed moving [nbresuse](https://github.com/yuvipanda/nbresuse) into the jupyter-server org in [today's Jupyter Server meeting](https://github.com/jupyter-server/team-compass/issues/1#issuecomment-730514597). 

This project has gained a lot of momentum and Jupyter-server seems like a good home for this project. Plus, we can relieve @yuvipanda of the maintenance burden 😅 .

Creating this issue to track the transfer. See the discussion on nbresuse [here](https://github.com/yuvipanda/nbresuse/issues/62#issuecomment-730495822).

**Comment by yuvipanda** [comment]
\o/ Hello! Thank you very much for opening this and discussing it during the meeting. I'd love to do so, but with the name 'jupyter-server-resuse' or 'jupyter-resource-usage' (or similar) - trying to remove the 'nbX' naming pattern. How does that sound?

**Comment by jtpio** [comment]
Sounds good to me, thanks Yuvi!

`jupyter-resource-usage` might sounds a little bit more user friendly and explicit than `resuse`?

**Comment by jasongrout** [comment]
> `jupyter-resource-usage` might sound a little bit more user friendly and explicit than `resuse`?

+1. I can't ever pronounce `resuse` right - I always start saying it one way, abort halfway through when it is not making sense, remember what it is supposed to stand for, then try to repronounce it several times in my head to get it right.

**Comment by yuvipanda** [comment]
Yeah, my preference is also for jupyter-resource-usage. This way, the package can also be called that, and nbresuse can be forever compatible for current users.

**Comment by yuvipanda** [comment]
I've renamed the project, but need permissions in jupyter-server org to actually do the transfer. Anyone add me temporarily?

I'd like to keep merge rights here afterwards too, if that's ok :)

**Comment by jtpio** [comment]
> I've renamed the project, but need permissions in jupyter-server org to actually do the transfer. Anyone add me temporarily?

cc @afshin who should be able to help with this

**Comment by echarles** [comment]
@yuvipanda Have added you as owner to the org for the repo transfer. I leave it up to @Zsailer to further update your membership.

**Comment by yuvipanda** [comment]
Done! \o/

I guess now we can start making releases under 'jupyter-resource-usage' rather than 'nbresuse'.

**Comment by jtpio** [comment]
Nice!

> I guess now we can start making releases under 'jupyter-resource-usage' rather than 'nbresuse'.

Opened https://github.com/jupyter-server/jupyter-resource-usage/issues/73 to track this.

Some remaining items that come to mind to finish the transition:

- [ ] Add a "General Jupyter contributor guidelines" section to CONTRIBUTING.md, similar to https://github.com/jupyter-server/jupyter_server/blob/master/CONTRIBUTING.rst#general-jupyter-contributor-guidelines. Or a "Community Guidelines and Code of Conduct" that points to https://jupyter.readthedocs.io/en/latest/community/content-community.html

**Comment by jtpio** [comment]
FYI, I also create the `jupyter-server` organization on npm, in case we want to publish packages there. For example the lab extensions package for `jupyter-resource-usage`, which could be named `@jupyter-server/jupyter-resource-usage`.

**Comment by Zsailer** [comment]
Closing, since this happened already! 🚀  😎
