### ISSUE TITLE
Scipy update

### ISSUE THREAD

**Issue by jasongrout** [jupyter-server/team-compass#31]
We're giving a very short lightning talk on Project Jupyter updates for the Scipy community at scipy this week (3 minutes for all of Jupyter!). If you had 10-20 seconds to communicate one major new thing to the Scipy community, what would it be?

**Comment by Zsailer** [comment]
Closing this issue, since SciPy has passed. @jasongrout, @blink1073, others and I worked together to give the Jupyter Server update. Big thank you to @marthacryan
