### ISSUE TITLE
New repo for Headless/Scheduled Notebooks

### ISSUE THREAD

**Issue by 3coins** [jupyter-server/team-compass#34]
There is on-going work on supporting running notebooks as jobs from anywhere Jupyter is running. [\#957](https://github.com/jupyter-server/jupyter_server/pull/957) showcases the concepts, components, and features of this extension. The goal here is to offer this to Jupyter (notebook, lab, hub) users as a new server extension under the `jupyter-server` org. Please vote here for setting up this repo. 

**Note**: One of the comments in the server meeting was bundling the UI and the server api in a single extension (Currently, we have separate extensions for these), since the UI depends on the server api. We will go ahead with this option and bundle the UI along with the server apis. 

cc @Zsailer

**Comment by 3coins** [comment]
The proposed name for the new repo is **jupyter-scheduler**. @Zsailer Can you help with creating the new repo and adding permissions so I can push to it.

**Comment by Zsailer** [comment]
Yes! I'll do that now. 

Closing the loop here—this move was officially approved by the Jupyter Server Team in a private vote. Thanks, @3coins, for the great work here!

**Comment by Zsailer** [comment]
https://github.com/jupyter-server/jupyter-scheduler

Done. 🚀 

Closing this issue here 😎

**Comment by 3coins** [comment]
Great! Thanks @Zsailer
