### ISSUE TITLE
Move jupyter/nb2kg to jupyter_server and archive repo

### ISSUE THREAD

**Issue by kevin-bates** [jupyter-server/team-compass#42]
The [`jupyter/nb2kg`](https://github.com/jupyter/nb2kg) repository houses the NB2KG server extension used to configure a Notebook server to communicate with a Gateway server (running either Jupyter Kernel Gateway or Jupyter Enterprise Gateway).  This server extension has been obsolete since its functionality was introduced into the `gateway` package of Notebook versions >= 6.0 and all Jupyter Server versions.

I would like to propose two changes relative to this repository:

1. Since the two related Gateway projects are already in the Jupyter Server organization, I think it makes sense to also have the `nb2kg` repository in that same organization and propose it be moved into `jupyter_server/nb2kg`.
2. Because this repository is essentially obsolete, yet continues to get dependabot alerts that it needs its dependency on notebook to be >= `6.4.12`, where it should not be used anyway, I think it best that the repository be archived.

I will hold off on any changes until we've decided if zero, one, or both of these changes should be made.

**Comment by blink1073** [comment]
I think if we're just going to archive it we should leave it in the `jupyter` org so it is more discoverable if someone was previously using it.

**Comment by kevin-bates** [comment]
That makes sense.

**Comment by kevin-bates** [comment]
Per today's [Jupyter Server/Kernels team meeting](https://github.com/jupyter-server/team-compass/issues/15#issuecomment-1319024800)  we felt (within the meeting) that archiving jupyter/nb2kg in-place is probably the best step moving forward (in line with @blink1073's [suggestion](https://github.com/jupyter-server/team-compass/issues/42#issuecomment-1316065789)).  I've been asked to poll @jupyter-server/jupyter-server-council regarding the repository's archival.  In the meantime, I've commented on an _existing_ [issue](https://github.com/jupyter/nb2kg/issues/49) in the nb2kg repo (which is 2+ years old) indicating the (new) desire to archive the repository.

### Polling
Polling is open to all members of the Jupyter Server Council.  Anyone is free to comment.

Using the built-in emojis, please indicate approval to archive the nb2kg repository within the jupyter organization using :+1: and its disapproval using :-1:.  If you'd like to further discuss its future, please feel free to comment separately.

Thank you.

**Comment by kevin-bates** [comment]
Sorry, this should have been closed with the previous comment.
