### ISSUE TITLE
JupyterCon 2023 Proposal

### ISSUE THREAD

**Issue by Zsailer** [jupyter-server/team-compass#43]
Hey Team! 

As we discussed in yesterday's meeting, our team should propose a talk for JupyterCon 2023 to give an update on Jupyter Server.

Opening this issue to track this task—deadline if December 15th.

If you'd be interested in representing the Jupyter Server Team and speaking at JupyterCon this year, please let the team know here! 😎 Anyone interested in speaking should plan to make the trip to Paris in May 2023. If we have multiple people interested in speaking, that's great! The more the merrier! 

I'm planning to submit (at least) one other talk, but I'm happy to help author this talk and/or present if needed. That said, I'd love to give the opportunity for other's on the team to present instead!  

@jupyter-server/jupyter-server-council

**Comment by Zsailer** [comment]
To kick off the discussion, here's a possible first draft, rough outline:

1. Brief Background
    1. what is Jupyter Server?
    2. where does Jupyter Server fit in the Jupyter stack/ecosystem
1. Where Jupyter Server is today (highlight 2.0 features).
    1. Present this section using live demos.
    1. Extendable (via server extensions)
    1. Customizable (via configurables, e.g. all the managers)
    1. Auth, Identity, Events, Kernel Websockets
1. Some ideas about where Jupyter Server is headed.
    1. More pluggability (i.e. should everything be a server extension?)
    1. More explicit abstractions/schemas 
    1. Jupyverse as alternative implementation
    1. More Enterprise-able?  
1. How to get involved/contribute/help?
    1. Introduction to "Contributing Hour"
    3. Highlight a couple of threads where discussions about "future directions" is happening.

**Comment by davidbrochart** [comment]
I guess I'm in a good position to present, not just geographically :smile: 
I think we should also talk about the contents API that is shifting to RTC, and [jupyter_server_ydoc](https://github.com/jupyter-server/jupyter_server_ydoc)/[ypy-websocket](https://github.com/y-crdt/ypy-websocket).

**Comment by Zsailer** [comment]
Sweet! I've added it to my outline above 🚀

**Comment by Zsailer** [comment]
Here is my attempt at a first draft. Thoughts? 

https://hackmd.io/tSVyycq0RHG_dfGOHzY8yQ

**Comment by kevin-bates** [comment]
Hey @Zsailer - thanks for starting this!  When I try to access this, I get a `403 Forbidden`.  Is there something I (and possibly others) need to do to gain access?

**Comment by Zsailer** [comment]
Ah, sorry about that. I've opened it up now!

**Comment by kevin-bates** [comment]
Looks good - thank you.

**Comment by davidbrochart** [comment]
Great @Zsailer, thanks a lot!
