### ISSUE TITLE
Meetings during the holidays

### ISSUE THREAD

**Issue by Zsailer** [jupyter-server/team-compass#44]
Hi folks, creating this poll here to see if folks would like to meet during the holidays. There are two weeks in questions here, December 22nd and December 29th. The next two comments will be separate polls for each. 
 
Please add a :+1: if you're available and interested on having a meeting on the specific day. Otherwise add a :-1: if you're unavailable or plan to skip to that meeting. 

If we don't have at least 3 team members committed to a meeting, we should cancel it officially and remove it from the calendar so we don't have folks from the community show up to an empty room. :) 

Thank you all!

@jupyter-server/jupyter-server-council

**Comment by Zsailer** [comment]
Poll for Thursday, December 22nd. If you plan to attend, please at a :+1:? If not, please add a :-1:.

**Comment by Zsailer** [comment]
Poll for Thursday, **December 29th**. If you plan to attend, please at a :+1:? If not, please add a :-1:.

**Comment by Zsailer** [comment]
Based on the polls above, I am going to remove the December 29th meeting from our public calendar. 

We'll leave December 22nd for now. If we don't have a 3rd :+1: by Wednesday, 8am (pacific), I'll remove it from the calendar as well.

Our first official meeting in the new year will be January 5th

**Comment by Zsailer** [comment]
I'm removing our December 22nd meeting from the calendar as well. If anyone wants to stop by anyways to hang out, please do so! The room is open for a social hour 😃.

**Comment by blink1073** [comment]
Closing since we're back in action!
