### ISSUE TITLE
Add triage rights

### ISSUE THREAD

**Issue by fcollonval** [jupyter-server/team-compass#46]
### Problem

I'm using with GitHub projects. To be able to set some metadata to issues, the user needs rights to do so that I'm lacking

### Proposed Solution

Is it possible to grant me triage rights?

**Comment by davidbrochart** [comment]
I sent you an invitation to be a member of the `jupyter-server` organization, let me know if this is enough.

**Comment by fcollonval** [comment]
Yes it is, thanks @davidbrochart
