### ISSUE TITLE
New repo for gateway-provisioners

### ISSUE THREAD

**Issue by kevin-bates** [jupyter-server/team-compass#47]
Hello,

The [gateway_provisioners repo](https://github.com/gateway-experiments/gateway_provisioners) currently resides in the gateway-experiments organization, which is where a few _experimental_ projects reside to complete POCs, etc.  With its 0.1.0 release, I would like to propose that it be moved into the jupyter-server organization so it can reside alongside the existing Gateway projects (Enterprise Gateway and Kernel Gateway).  In addition to perhaps making the project more available to contributions, we can also more safely leverage things like jupyter-releaser (and its use of tokens during release builds, etc.).

gateway_provisioners provides [kernel provisioners](https://jupyter-client.readthedocs.io/en/latest/provisioning.html) for launching and managing kernel lifecycles in Kubernetes, Docker, DockerSwarm, SSH, and Hadoop Yarn clusters.  Because these are merely kernel provisioners, they are available to projects other than the Gateway projects.  (Fun fact, they are NOT currently available to EG until its 4.0 release.)  This repo was originally named remote-provisioners, but I felt that name was too generic, [among other things](https://github.com/gateway-experiments/gateway_provisioners/issues/36).  

I'd like to add this topic to this week's [Server/Kernels Team Meeting](https://github.com/jupyter-server/team-compass#weekly-team-meetings), at which time I'm hoping we can reach a consensus.

**Comment by Zsailer** [comment]
This proposal was officially accepted by a (private) team vote! Thanks and congratulations @kevin-bates! 

Feel free to transfer the repo whenever you're ready and close this issue once that's finished! 🚀

**Comment by kevin-bates** [comment]
Repo has been transferred - thanks everyone!
