### ISSUE TITLE
Name a core Jupyter Server Team.

### ISSUE THREAD

**Issue by Zsailer** [jupyter-server/team-compass#5]
I'd like to propose a Jupyter Server Team. 

This would name individuals who regularly contribute to the Jupyter Server organization+projects as "members" of the Team.

I propose we adopt a similar model to the Jupyterhub/Binder team: https://jupyterhub-team-compass.readthedocs.io/en/latest/team.html

Members would have the following privileges (pulling from JupyterHub's model):
* recognition
* team members can speak for the project in public
* merge privileges on the project repositories
* nominating other individuals to team membership

**Comment by Zsailer** [comment]
An initial cohort, based on long-time, regular attendance to our weekly meeting might be:

* me (@Zsailer)
* Kevin Bates (@kevin-bates)
* Eric Charles (@echarles)
* Vidar Fauske (@vidartf)
* Afshin Darian (@afshin)

Also (if they're up for it) I think the following people would make fantastic team members based on their previous contributions:

* Steve Silvester (@blink1073)
* Mariko Wakabayashi (@mwakaba2)
* Jeremy Tuloup (@jtpio)

Am I missing anyone?

Also, if I named you above but you're not interested in team membership, let me know (no hard feelings 😉 ).

**Comment by Zsailer** [comment]
Adding this topic to the next Jupyter Server meeting 🚀

**Comment by Zsailer** [comment]
Reviving the discussion on this issue. 

With the recent merge of the [Governance Software Steering Council](https://github.com/jupyter/governance/pull/103), I think we should move forward with naming an "official" team. 

To make this easy (and since they did all the heavy lifting already 😅 ), I'd like to borrow most of the process, structure, and language from [Binder's team-compass docs](https://jupyterhub-team-compass.readthedocs.io/en/latest/binder/governance.html#team-responsibilities).

Specifically, I'd like to highlight their team roles: red team, blue team, and green team. I propose we adopt this structure.

Finally, during this initial bootstrapping of the team, we obviously don't have a way to nominate one another. Instead, I ask everyone who actively contributes to Jupyter Server (in some way) to review the roles on that Binder page and self-nominate yourself for a team color. We can discuss this further at our next meeting. After next meeting, I'll submit a PR with a list of team members to name the initial team. I'll ping you directly if we don't hear from you before then.

**Comment by blink1073** [comment]
I'd like to nominate myself as a Red Team member.

**Comment by Zsailer** [comment]
I'd also like to nominate myself as a Red Team member.

**Comment by Zsailer** [comment]
I should mention, I'm also interested in being the "Team Lead". 

Team Lead role will be Jupyter Server's representative on the Software Steering Council. If anyone has any questions about this, feel free to ping me.

I think this position should be nominated, then elected by team members moving forward. We can discuss this at the next meeting too.

**Comment by echarles** [comment]
I'd like to nominate myself as Green Team member.

**Comment by afshin** [comment]
I think Zach being Team Lead and also the representative on the Software Steering Council makes perfect sense. I'd just like to note that if any other teams look to this thread as a guide, we are not taking a stance on whether those two roles should be the same person. I can easily imagine a team that has enough going on where Team Lead is one person and SSC representative is a different person.

**Comment by afshin** [comment]
I'd like to nominate myself for Green Team now (Nov. 2021) and Red Team after the new year when I return from leave.

**Comment by Zsailer** [comment]
> we are not taking a stance on whether those two roles should be the same person. I can easily imagine a team that has enough going on where Team Lead is one person and SSC representative is a different person.

Great point, @afshin! I had it in my head that these were the same person, but I totally agree with this distinction. Thank you for clarifying!

**Comment by kevin-bates** [comment]
I'd like to nominate myself as a Red Team member.

**Comment by davidbrochart** [comment]
I'd like to nominate myself as a Blue Team member.

**Comment by Zsailer** [comment]
@jess-x and @mwakaba2, you both deserve membership. 😎

**Comment by mwakaba2** [comment]
I'd love to join as a Red Team member!

**Comment by jess-x** [comment]
🙋‍♀️ I would love to join as a Blue Team member!!

**Comment by jtpio** [comment]
Happy to join as a Green Team member for now.

**Comment by vidartf** [comment]
I'm happy to join the Red Team (if I have understood the teams correctly 😄 )

**Comment by kevin-bates** [comment]
After further consideration, I think it would be best to start the year on the **green team**. Thank you.

**Comment by echarles** [comment]
Based on explanations at last server meeting, I'd like to nominate myself as Red Team member (instead of initially Green).

**Comment by Zsailer** [comment]
Based on today's Jupyter Server meeting, we're going to absolve the notion of team colors. 

Instead, we'll have something like "Active" and "Inactive" team members. 

Here's what I propose these two terms mean:

* Active team members get a vote (and are expected to participate in voting) whenever the occasion arises. Inactive members do not.
* Team members should communicate when they are going inactive and vice versa, and members can freely pass between those two states. E.g. if you're out on vacation/leave for a few weeks, you can temporarily go inactive, then become active on return.
* Every six months, we'll send out a message to everyone on the current active team asking if they still consider themselves active. If not (or no response is given), it will be assumed that they have gone inactive. This will help keep the active team up-to-date. Remember, an inactive member can return at any time by simply changing their status on the team-compass page. 
* Active members count towards a quorum number during a voting situation; inactive members do not.
* To become an active member, a nomination is requires by a currently active member.

**Comment by Zsailer** [comment]
For full transparency, I wanted to share this note from today's meeting.

* We (accidentally, :sweat_smile:) side-stepped the official approach, [defined by Jupyter Governance](https://jupyter.org/governance/bootstrapping_decision_making.html#proposed-framework), to form a decision making body.
* This process requires a current steering council member to seed (i.e. nominate an initial member). Together, the gradually growing team continues nominating new members. 
* Large, diverse, and inclusive teams is encouraged.
* We, instead, self nominated ourselves, proposed by @Zsailer. 
* @afshin mentioned in the meeting that this is might be okay, because
  * we made a good-faith effort at nominating people
  * the current group that's actively participating is relatively small
  * we arrived at the same results anyways.
* For other teams who might be observing this process, **do not** follow our process :laughing: 

My apologies for leading us away from the defined process—I had, somehow, missed this section of the governance docs. A huge thank you to @afshin for raising this point and advocating for transparency here.  

If anyone still has concerns, please don't hesitate to reach out to privately.

**Comment by Zsailer** [comment]
Given that we are likely going to absolve team colors, I am planning to add all people who nominated themselves as blue + red as active team members and green as inactive team members.

**Comment by kevin-bates** [comment]
Thanks for the updates @Zsailer - I agree this is a clearer model.  In light of these changes and the fact that I hadn't realized these "teams" were scoped at the organization level (thinking only repo-level initially) then I'd like to remove myself from "green" and ask for a nomination to "active".

**Comment by echarles** [comment]
Thx for leading this process @Zsailer 

I have read https://github.com/jupyter-server/team-compass/pull/14 and the changes are great.

They bring clarity and simplification. Is the PR ready to be approved? Not sure what we do with all the existing approvals. I guess if someone as approved but has more thoughts regarding the change, he can post his question/comment. 

When do we target to merge the PR?

**Comment by Zsailer** [comment]
Thanks @echarles! I went ahead and requested another review from you in the Github UI. I think we should merge this at next week's server meeting if there are no objections.

**Comment by Zsailer** [comment]
We're live! https://jupyter-server-team-compass.readthedocs.io/en/latest/
