### ISSUE TITLE
Create new, empty repo to facilitate collaboration on the "notebook state" problem

### ISSUE THREAD

**Issue by Zsailer** [jupyter-server/team-compass#52]
Hi folks,

In yesterday's server meeting, I proposed creating a new repo to explore solutions to the issue raised here: [Proposal: Restore Notebook execution progress when a browser page is reload](https://github.com/jupyter-server/jupyter_server/issues/1274#issuecomment-1593524857)

We've seen a lot of interest on this issue from people representing different organizations. I'd like to focus this energy to a single place on Github so we can easily collaborate. This work will likely be larger than a single PR and require some explorative work. For that reason, I'd like to focus this work in a separate repo.

I'll open a vote in our private council repo. @jupyter-server/jupyter-server-council 

In the meantime, what should we call this repo if it gets created?

**Comment by Zsailer** [comment]
Pinging folks who've been involved in the conversations: @matthewwiese @skukhtichev and @parul100495

**Comment by Zsailer** [comment]
> In the meantime, what should we call this repo if it gets created?

How about: **jupyter-server/jupyter_message_replay** ?

**Comment by matthewwiese** [comment]
@Zsailer `jupyter-server/jupyter_message_replay` is succinct enough for me!

**Comment by parul100495** [comment]
The name looks good to me as well.

**Comment by Zsailer** [comment]
The Server Team voted in favor of creating a new repo for this work 🚀! (8 Yes, 7 Abstain). 

Let's create the repo during the meeting.

**Comment by Zsailer** [comment]
> How about "serverside-notebook-state"? "message replay" is one possible solution, but not the only one.

@ivanov true. The problem is a bit broader than the notebook too—e.g. kernel state (say for a console, not a notebook document) needs restoration too.

**Comment by matthewwiese** [comment]
@Zsailer Could you add a placeholder README to the `jupyter-server/message_replay` repo? GitHub won't let me fork it and open a PR with the extension cookiecutter template because the repository is empty

**Comment by Zsailer** [comment]
Thank you @blink1073!

**Comment by ivanov** [comment]
For anyone following along, here's the link: https://github.com/jupyter-server/message_replay
