### ISSUE TITLE
Membership maintenance check (2024) 

### ISSUE THREAD

**Issue by Zsailer** [jupyter-server/team-compass#56]
Hi all,

(following the lead from the [Kernel's Team here](https://github.com/jupyter/kernels-team-compass/issues/7)) 

One year has almost passed since the creation of this council and I wanted to trigger a [membership maintenance check](https://jupyter-server-team-compass.readthedocs.io/en/latest/team/becoming-member.html#membership-maintenance).

Please indicate below one way or the other if you would like to remain as an active member of this council, or if you prefer to become inactive at this time.

This poll will remain open until the **first week of January, 2024**, at which point we will assume an `inactive` role for anyone not participating.

- @damianavila
  - [x] remain active
  - [ ] go inactive 
- @kevin-bates 
  - [x] remain active
  - [ ] go inactive 
- @davidbrochart 
  - [x] remain active
  - [ ] go inactive 
- @echarles 
  - [x] remain active
  - [ ] go inactive 
- @SylvainCorlay 
  - [x] remain active
  - [ ] go inactive 
- @afshin 
  - [x] remain active
  - [ ] go inactive 
- @vidartf 
  - [x] remain active
  - [ ] go inactive 
- @rahul26goyal
  - [ ] remain active
  - [ ] go inactive 
- @ellisonbg
  - [x] remain active
  - [ ] go inactive 
- @ivanov
  - [x] remain active
  - [ ] go inactive 
- @3coins
  - [x] remain active
  - [ ] go inactive 
- @lresende 
  - [x] remain active
  - [ ] go inactive 
- @Zsailer 
  - [x] remain active
  - [ ] go inactive 
- @blink1073 
  - [x] remain active
  - [ ] go inactive 
- @willingc  
  - [x] remain active
  - [ ] go inactive

**Comment by ivanov** [comment]
no one has a monopoly on good ideas, but just want to mention that kernels team was [following the lead of foundations and standards council](https://github.com/jupyter/foundations-and-standards-team-compass/issues/1) :)
