### ISSUE TITLE
New SSC Representative Nomination

### ISSUE THREAD

**Issue by Zsailer** [jupyter-server/team-compass#65]
Hey all, 

I sent an email to our team's google group, but wanted to make a public post here for transparency. I'll update our docs here as soon as the new representative is picked.

I am switching roles to the EC and therefore stepping down as the Jupyter Server representative, effectively immediately. Replacing this position is fairly time-sensitive, given the upcoming vote on the [Linux Foundation Proposal](https://jupyter.org/governance/linux-proposal.html).  

Nominations for a new representative are open until Monday—the form can be found in the google group message. Please self-nominate, or reach out to anyone on the team you'd like to nominate. 

Thanks all! It's been a pleasure representing you this past year. Let me know if you have any questions.

**Comment by echarles** [comment]
Congratulations for your new role @Zsailer and overall, a huge thanks for the work you have been doing to make Jupyter Server a success. From the inception (extracting the server from notebook) and the work around the new extension system, ensuring backwards compatibility, gathering and motivating people on the calls, launching contributor hours, and I could continue with more. I truly have no words to thank you. Jupyter Server will miss you as representative and hope you will still find time to be around these org repositories.

**Comment by Zsailer** [comment]
❤️  Thank you, @echarles. I really appreciate that. I love this group. Ya'll are amazing! Keep building great things! 🚀

**Comment by Zsailer** [comment]
Closing, since nominations have passed and we'll reveal the new representative in today's meeting!
