### ISSUE TITLE
Cancel 25 March Meeting?

### ISSUE THREAD

**Issue by blink1073** [jupyter-server/team-compass#7]
Hi folks, a few of us are unavailable this Thursday.  I propose we cancel the meeting this week and pick back up on 1 April.

**Comment by afshin** [comment]
Sounds good. Thanks, Steve. Catch you all next week.

**Comment by kevin-bates** [comment]
I'll hang out for 5-10 minutes to let folks know and perhaps gather agenda items for next week.  Take care.
